# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wd < Formula
  desc ""
  homepage "https://github.com/onsd/wd"
  version "1.4.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.4.0/wd_1.4.0_darwin_amd64.tar.gz"
    sha256 "11b137e5555f29e73554db62bf5f8983f712112ab936b44a6c8234efa0725b9f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/onsd/wd/releases/download/v1.4.0/wd_1.4.0_darwin_arm64.tar.gz"
    sha256 "ec2beee5910b868547fbe8f0eeb6076d7aa7157069291b474f1e0dfe7efe92df"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.4.0/wd_1.4.0_linux_amd64.tar.gz"
    sha256 "a8eaf879d972759eedab5eb18386b22a67c0673749526adda64a4be05ae408e6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/onsd/wd/releases/download/v1.4.0/wd_1.4.0_linux_arm64.tar.gz"
    sha256 "3abecb815ef26bb6afed77d7149bca85899c3b2ffd0a06fe0a70a2d6d57d0bec"
  end

  def install
    bin.install "wd"
  end
end
