# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wd < Formula
  desc ""
  homepage "https://github.com/onsd/wd"
  version "1.2.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.2.1/wd_1.2.1_darwin_amd64.tar.gz"
    sha256 "300133b9fbd97f6b39238c19669124c4314a55846f9b80264e479fa928eeaf39"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/onsd/wd/releases/download/v1.2.1/wd_1.2.1_linux_amd64.tar.gz"
    sha256 "3bc5c6312d4331f975faa6414eebc3ccd171b41f718669dcd3296c1a1e8895b8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/onsd/wd/releases/download/v1.2.1/wd_1.2.1_linux_arm64.tar.gz"
    sha256 "95a78a7fb0a4db177d1415bd10856cfe689fdab89db2e19576d37873147a654d"
  end

  def install
    bin.install "wd"
  end
end
